server:
  port: 11120
spring:
  application:
    name: eureka-server
  profiles:
    active: local
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/

